### PR TITLE
Code request

### PR DESCRIPTION
**Pull request by kpomazi**
Hi Boris,

Your work is very inspiring!
I would appreciate the opportunity to view your source code, as you have mentioned this in the readme.

Thank you!

### CODE REVIEW

**Comment by thedarkrider69** [comment]
Hi Boris, thank for sharing your code, could you share the source code please a saint in readme?

Thx

**Comment by tsaiwilly** [comment]
Hi Boris,
Nice job! All the things you utilized are so attractive to me.
I would be very thankful to get the full code.
Many thanks in advance!
Best regards,

Willy

tsaiwilly0911@gmail.com

**Comment by KittyRong** [comment]
Hi Boris,

Lots of inspiring insights! These methods make sense and excited about your work.

Can you share me with the full code?

Thank you.

rongxiaohui@fuji.waseda.jp

**Comment by Crayfi** [comment]
Hello Boris!

I've read through your notebook and am very interested how you implemented things in your code. Could you please send a copy of your work to gamerv2008@gmail.com? 

Thank you!

**Comment by beyondcognition** [comment]
Hi Boris,

Very extensive work and research.
I would appreciate the opportunity to get a hands on & test on the code.
If it is possible, please email the code at atul.analyst@gmail.com

Thank and Regards,
Atul

**Comment by hjunleon** [comment]
Hi Boris, 

Thanks for covering this topic in great depth, with thorough descriptions of your thought process when choosing strategies. I would very much appreciate the opportunity to view your code! 

Here's my email: hjunleon@gmail.com
Thank you!

**Comment by sackio** [comment]
Hi Boris,
Fantastic project -- would you be willing to share the source code with me? My email is ben@sack.io
Thank you!
-Ben

**Comment by CompassLM** [comment]
Hi Boris,
Outstanding work! 
I've read through your notebook and would appreciate the opportunity to view your code if possible.
My email: compassxlm@gmail.com
Thank you!

**Comment by w1767** [comment]
Hi Boris, 
Thank you for sharing this great work. 

Could you please share the source code. I am currently doing a PhD in Machine Learning. 

My e-mail address is w1767944@my.westminster.ac.uk


Best regards,
George

**Comment by erezh31** [comment]
Boris,
Thank you!
Willl be happy to get the code: erez.study@gmail.com
Thank you

**Pull request closed without merging**
